export const actionType = {
    CHANGE_STATUS_TASK: 'CHANGE_STATUS_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    ACTIVE_CATEGORY: 'ACTIVE_CATEGORY',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    EDIT_CATEGORY: 'EDIT_CATEGORY',
    CREATE_TASK: 'CREATE_TASK'
};