export const actionType = {
  CHANGE_STATUS: 'CHANGE_STATUS',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  ACTIVE_CATEGORY: 'ACTIVE_CATEGORY',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  CREATE_TASK: 'CREATE_TASK'
};